# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt/convert_npy.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_convert(object):
    def setupUi(self, Dialog_convert):
        Dialog_convert.setObjectName("Dialog_convert")
        Dialog_convert.resize(465, 389)
        font = QtGui.QFont()
        font.setFamily("Arial")
        Dialog_convert.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/logo_app-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_convert.setWindowIcon(icon)
        self.layoutWidget = QtWidgets.QWidget(Dialog_convert)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 411, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_input_files = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_input_files.setFont(font)
        self.label_input_files.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_files.setObjectName("label_input_files")
        self.verticalLayout_16.addWidget(self.label_input_files)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.input_list_npy = QtWidgets.QListWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.input_list_npy.setFont(font)
        self.input_list_npy.setObjectName("input_list_npy")
        self.horizontalLayout_6.addWidget(self.input_list_npy)
        self.input_files_btn = QtWidgets.QToolButton(self.layoutWidget)
        self.input_files_btn.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.input_files_btn.setArrowType(QtCore.Qt.NoArrow)
        self.input_files_btn.setObjectName("input_files_btn")
        self.horizontalLayout_6.addWidget(self.input_files_btn)
        self.verticalLayout_16.addLayout(self.horizontalLayout_6)
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog_convert)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 160, 411, 61))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_17.addWidget(self.label_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.save_files_path = QtWidgets.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.save_files_path.setFont(font)
        self.save_files_path.setObjectName("save_files_path")
        self.horizontalLayout_7.addWidget(self.save_files_path)
        self.save_files_btn = QtWidgets.QToolButton(self.layoutWidget_2)
        self.save_files_btn.setObjectName("save_files_btn")
        self.horizontalLayout_7.addWidget(self.save_files_btn)
        self.verticalLayout_17.addLayout(self.horizontalLayout_7)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog_convert)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 230, 361, 72))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mat_file = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.mat_file.setFont(font)
        self.mat_file.setChecked(True)
        self.mat_file.setObjectName("mat_file")
        self.horizontalLayout.addWidget(self.mat_file)
        self.hdf5_file = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hdf5_file.setFont(font)
        self.hdf5_file.setObjectName("hdf5_file")
        self.horizontalLayout.addWidget(self.hdf5_file)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.csv_tab_file = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.csv_tab_file.setFont(font)
        self.csv_tab_file.setObjectName("csv_tab_file")
        self.horizontalLayout_2.addWidget(self.csv_tab_file)
        self.csv_comma_file = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.csv_comma_file.setFont(font)
        self.csv_comma_file.setObjectName("csv_comma_file")
        self.horizontalLayout_2.addWidget(self.csv_comma_file)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog_convert)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 340, 411, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.close_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.close_btn.setFont(font)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_3.addWidget(self.close_btn)
        spacerItem = QtWidgets.QSpacerItem(97, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.convert_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.convert_btn.setFont(font)
        self.convert_btn.setObjectName("convert_btn")
        self.horizontalLayout_3.addWidget(self.convert_btn)
        self.progressBar = QtWidgets.QProgressBar(Dialog_convert)
        self.progressBar.setGeometry(QtCore.QRect(50, 310, 371, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.done = QtWidgets.QLabel(Dialog_convert)
        self.done.setGeometry(QtCore.QRect(200, 310, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.done.setFont(font)
        self.done.setAlignment(QtCore.Qt.AlignCenter)
        self.done.setObjectName("done")

        self.retranslateUi(Dialog_convert)
        QtCore.QMetaObject.connectSlotsByName(Dialog_convert)

    def retranslateUi(self, Dialog_convert):
        _translate = QtCore.QCoreApplication.translate
        Dialog_convert.setWindowTitle(_translate("Dialog_convert", "Convert npy files"))
        self.label_input_files.setText(_translate("Dialog_convert", "npy files to convert"))
        self.input_files_btn.setText(_translate("Dialog_convert", "..."))
        self.label_6.setText(_translate("Dialog_convert", "Path to save files"))
        self.save_files_btn.setText(_translate("Dialog_convert", "..."))
        self.label_7.setText(_translate("Dialog_convert", "Select file type"))
        self.mat_file.setText(_translate("Dialog_convert", "Matlab file (mat)"))
        self.hdf5_file.setText(_translate("Dialog_convert", "HDF5 file (h5)"))
        self.csv_tab_file.setText(_translate("Dialog_convert", "CSV file (\"tab\" separator)"))
        self.csv_comma_file.setText(_translate("Dialog_convert", "CSV file (\",\" separator)"))
        self.close_btn.setText(_translate("Dialog_convert", "Close"))
        self.convert_btn.setText(_translate("Dialog_convert", "Convert"))
        self.done.setText(_translate("Dialog_convert", "DONE!"))
import img.resource


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog_convert = QtWidgets.QDialog()
    ui = Ui_Dialog_convert()
    ui.setupUi(Dialog_convert)
    Dialog_convert.show()
    sys.exit(app.exec_())
